// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: message.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Proto
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Ping : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"version")]
        public uint Version { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"network_id")]
        public uint NetworkId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"timestamp")]
        public long Timestamp { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"src_addr")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SrcAddr { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"src_port")]
        public uint SrcPort { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"dst_addr")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DstAddr { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Pong : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"req_hash")]
        public byte[] ReqHash { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"services")]
        public ServiceMap Services { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"dst_addr")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DstAddr { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DiscoveryRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"timestamp")]
        public long Timestamp { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DiscoveryResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"req_hash")]
        public byte[] ReqHash { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"peers")]
        public global::System.Collections.Generic.List<Peer> Peers { get; } = new global::System.Collections.Generic.List<Peer>();

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
