image: microsoft/dotnet:3.0-sdk

stages:
  - build
  
variables:
  project: "zero.web"

before_script:
  - "dotnet --version"
  - "dotnet restore" 
  - "apt-get update"
  - "apt install curl"
  - "bash -c 'curl -sL https://deb.nodesource.com/setup_10.x | bash -'"
  - "apt install nodejs"


build:
  stage: build
  variables:
    build_path: "$project"  
  script:
    - "cd $project"
    - "npm install"
    - "cd .."
    - "dotnet build zero.api"
    - "dotnet build zero.web"
