image: mcr.microsoft.com/dotnet/sdk

stages:
  - build
  
variables:
  project: "zero.sync"

before_script:
  - "dotnet --version"
  - "git submodule init"
  - "git submodule update"
  - "dotnet restore"

build:
  stage: build
  variables:
    build_path: "$project"
  script:
    - "cd $build_path"
    - "dotnet build"

