image: mcr.microsoft.com/dotnet/sdk:6.0

stages:
  - build
  - tests
  
variables:
  project: "zero.sync"
  LOGFILEPATH: "JUnitTestLogFile.xml"

before_script:
  - "dotnet --version"
  - "git submodule init"
  - "git submodule update"
  - "dotnet restore"

build:
  stage: build
  variables:
    build_path: "$project"
  script:
    - "cd $build_path"
    - "dotnet build"

test:
    stage: tests
    script:
    - dotnet test --logger "junit;LogFilePath="$LOGFILEPATH
    artifacts:
        when: always
        paths:
        - zero.test/$LOGFILEPATH
        reports:
            junit: zero.test/$LOGFILEPATH

